### PR TITLE
[mpm] Integration test support package and deploy command

### LINKED ISSUE #3574: [Feature Request] mpm integration-test support `package` and `deploy` command
# Feature Request

**Describe the Feature Request**

let mpm integration-test support `package` command, for build Starcoin package transaction.

Currently, We use the `publish` command to publish the modules to storage; it auto compiles the Move modules and builds package transaction.

But sometimes, We need to know the Package hash in integration-test, such as the two-phase upgrade.

So we need to support `package` and `deploy` commands in integration-test files.

**Describe Preferred Solution**

```move
//# package
module default::MyModule{

}

// submit the Upgrade plan.

//# deploy $.package[0].package_file

```

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
Yes / No _(Help can be provided if you need assistance submitting a PR)_

### PR DESCRIPTION
**Pull request by jolestar**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: resolve #3574 

## What is the new behavior?

-
-
-

## Other information

https://github.com/starcoinorg/move/pull/11

TODO: 测试用例

### CODE REVIEW

**Review by 0xpause — APPROVED** [review]

**Comment by baichuan3** [comment]
mpm release 和 submit_upgrade_plan 是在集成测试里执行，还是单独命令行执行？

**Comment by jolestar** [comment]
> mpm release 和 submit_upgrade_plan 是在集成测试里执行，还是单独命令行执行？

集成测试里运行

**Comment by baichuan3** [comment]
> > mpm release 和 submit_upgrade_plan 是在集成测试里执行，还是单独命令行执行？
> 
> 集成测试里运行

给个集成测试里调用  mpm release 和 submit_upgrade_plan 的例子？

**Comment by jolestar** [comment]
> > > mpm release 和 submit_upgrade_plan 是在集成测试里执行，还是单独命令行执行？
> > 
> > 
> > 集成测试里运行
> 
> 给个集成测试里调用 mpm release 和 submit_upgrade_plan 的例子？

https://github.com/starcoinorg/starcoin/pull/3635

提供的是 package 和 deploy 命令。package 之后可以获取到 package_hash，然后执行 submit_upgrade_plan

**Pull request merged**
