### PR TITLE
remove Ofast on ubuntu22

### PR DESCRIPTION
**Pull request by nkysg**
## Pull request type
移除Ofast编译选项
需要在ubuntu18, ubuntu22上跑通所有历史区块才能合并到master

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

### CODE REVIEW

**Comment by nkysg** [comment]
和这个问题一样 https://github.com/starcoinorg/starcoin/issues/3831

**Comment by sanlee42** [comment]
Related to https://github.com/starcoinorg/starcoin/pull/3056/files#diff-1f291e353829de7fbcdfc0f4b2193c66c48111529ed30a68e4f2f5e3da4722ce

**Comment by nkysg** [comment]
> Need unit tests, Related to https://github.com/starcoinorg/starcoin/pull/3056/files#diff-1f291e353829de7fbcdfc0f4b2193c66c48111529ed30a68e4f2f5e3da4722ce

I will add unit test

**Review by sanlee42 — APPROVED** [review]

**Comment by nkysg** [comment]
https://github.com/starcoinorg/starcoin/pull/3848 has fix this problem, so close it

**Pull request closed without merging**
