### PR TITLE
Use 0 as dag fork number in test case

### PR DESCRIPTION
**Pull request by jackzhhuang**
1, use 0 as dag fork number in test case
2, use selected parent in tips as the new block header's parent if tips are descendants of the header

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

### CODE REVIEW

**Comment by nkysg** [comment]
Please open the CI build and test.

**Comment by jackzhhuang** [comment]
> Please open the CI build and test.

I found some test cases still failed after merged Simon's latest commit.
Need more time to fix.

**Comment by nkysg** [comment]
> > Please open the CI build and test.
> 
> I found some test cases still failed after merged Simon's latest commit. Need more time to fix.

Got it.

**Comment by nkysg** [comment]
see https://github.com/starcoinorg/starcoin/pull/4130.

**Pull request closed without merging**
