### PR TITLE
support txn-> block mapping, and add rpc types

### PR DESCRIPTION
**Pull request by lerencao**
- new column family added.
- rpc types are basiclly done.
- tranasction info view is using txn-> block mapping.

What's left to bedone are just reimplmenting other rpc apis to adopt the new jsonrpc types.

### CODE REVIEW

**Comment by lerencao** [comment]
dont merge until https://github.com/starcoinorg/SIPs/pull/1 is merged

**Review by jolestar — COMMENTED** [review]
我的建议都写到  https://github.com/starcoinorg/SIPs/pull/1 这里了。   @fanngyuan 看看

**Comment by lerencao** [comment]
> 我的建议都写到 [starcoinorg/SIPs#1](https://github.com/starcoinorg/SIPs/pull/1) 这里了。 @fanngyuan 看看

嗯，今天再改下

**Comment by lerencao** [comment]
close this in favor of #1673

**Pull request closed without merging**
