### PR TITLE
fix compilation issue of cyptonight on windows

### PR DESCRIPTION
**Pull request by jiangying000**
## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: try fix https://github.com/starcoinorg/starcoin/pull/3710#issuecomment-1259177757

## What is the new behavior?

-
-
-

### CODE REVIEW

**Comment by jolestar** [comment]
有 windows 下试过吗？

**Comment by jiangying000** [comment]
> 有 windows 下试过吗？

我还没有 windows 机器，可以用这个跑release windows asset CI 吗

**Comment by jolestar** [comment]
@LemonHX 帮忙试试？

**Comment by jiangying000** [comment]
在 windows 环境，可以 cargo build  编译过，工具链是 1.63.0-x86_64-pc-windows-msvc (override)

**Pull request merged**
