### PR TITLE
Add stdlib tests for upgrading from v11 to v12

### PR DESCRIPTION
**Pull request by 0xpause**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Other (please describe): unit test

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

- Add stdlib tests for upgrading from v11 to v12
- Upgrade stdlib to latest
- Close #3786 

## Other information

- Wait for starcoin-framework v12 release.

### CODE REVIEW

**Review by jolestar — APPROVED** [review]
LGTM

**Comment by jolestar** [comment]
There is an integration test failed:
```
✘ Then cmd: "account execute-function --function
  0x1::GasOracleProposalPlugin::create_oracle_add_proposal -t
  0x1::StarcoinDAO::StarcoinDAO -t 0x1::DummyToken::DummyToken  --arg b"desc"
  --arg 0 --arg {{$.account[0].ok.account.address}} -b"
                                                     features/cmd.feature:218:5
———— ! Step failed: ———————————————————————— testsuite/tests/steps/cmd.rs:64:21
  error occurred when decoding 2nd parameter , the type should be Vector(U8)
```

@sanlee42 help review

**Comment by 0xpause** [comment]
> There is an integration test failed:
> 
> ```
> ✘ Then cmd: "account execute-function --function
>   0x1::GasOracleProposalPlugin::create_oracle_add_proposal -t
>   0x1::StarcoinDAO::StarcoinDAO -t 0x1::DummyToken::DummyToken  --arg b"desc"
>   --arg 0 --arg {{$.account[0].ok.account.address}} -b"
>                                                      features/cmd.feature:218:5
> ———— ! Step failed: ———————————————————————— testsuite/tests/steps/cmd.rs:64:21
>   error occurred when decoding 2nd parameter , the type should be Vector(U8)
> ```
> 
> @sanlee42 help review

感觉这个测试也是可以放到 integration-test 里面？

**Comment by jolestar** [comment]
> 
> 感觉这个测试也是可以放到 integration-test 里面？

是可以，不过 integration-test 的测试框架不现在还不支持设置 gas token 的参数，需要修改一下，所以当时先放这里了。

**Pull request merged**
