### PR TITLE
rolback dag-effective-height to zero

### PR DESCRIPTION
**Pull request by simonjiao**
* init dag when executing genesis block
* fix check_dag_type
* restore dag_fork_height
* build dev network as dag chain

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

### CODE REVIEW

**Comment by simonjiao** [comment]
failed test cases in test_block_chain.rs when configuring test network as dag chain：
-     test_block_chain_for_dag_fork
-     test_block_chain_txn_info_fork_mapping
-     test_find_ancestor_fork:
-     test_random_uncle
-     test_switch_epoch
-     test_uncle
-     test_uncle_exist
-     test_uncle_in_diff_epoch
-     test_uncle_son

**Comment by simonjiao** [comment]
failed test (incompleted)
`test_verified_client_for_dag`

**Comment by jackzhhuang** [comment]
> failed test (incompleted) `test_verified_client_for_dag`

Ignore or delete this case because get_dag_block_children will not be used for now.

**Comment by simonjiao** [comment]
> > failed test (incompleted) `test_verified_client_for_dag`
> 
> Ignore or delete this case because get_dag_block_children will not be used for now.

Please give starcoin-sync a full test run to check out other failed or timeout test cases. And remove more unused codes, DONOT waste other members' time!

**Pull request closed without merging**
