### PR TITLE
update move to a new revision

### PR DESCRIPTION
**Pull request by JerryKwan**
update move to a new revision which fix the test failure issue

Current implementation of starcoin/move has some problems when processing account address, and some test cases failed when running `cargo test`. Update starcoin to a new revision which have fixed the address problems
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

This is just a temporary solution, need to update to an official starcoin/move git revision once https://github.com/starcoinorg/move/pull/10 has been merged

Issue Number: https://github.com/starcoinorg/move/issues/8

## What is the new behavior?

-
-
-

### CODE REVIEW

**Comment by nkysg** [comment]
hi @JerryKwan , you can commit move  change to starcoinorg/move:starcoin-main

**Comment by JerryKwan** [comment]
@nkysg This is the PR to starcoin/move https://github.com/starcoinorg/move/pull/10

**Comment by jolestar** [comment]
@JerryKwan can you help rebase this pr and fix test cases?

**Comment by JerryKwan** [comment]
@jolestar The test case failed was introduced by these changes in starcoin/move
https://github.com/starcoinorg/move/blob/starcoin-main/language/move-core/types/src/language_storage.rs#L129-L135
Will change the test case accordingly

**Review by jolestar — APPROVED** [review]

**Comment by jolestar** [comment]
@JerryKwan please help resolve the conflicting files.

**Review by nkysg — APPROVED** [review]

**Comment by jolestar** [comment]
@JerryKwan the Cargo.lock is change.

**Comment by JerryKwan** [comment]
> @JerryKwan the Cargo.lock is change.

@jolestar Yes, Cargo.lock has changed. Seems like Cargo.lock changes now and then, wondering if it is necessary to update Commit the changes of Cargo.lock all the time

**Comment by jolestar** [comment]
> > @JerryKwan the Cargo.lock is change.
> 
> @jolestar Yes, Cargo.lock has changed. Seems like Cargo.lock changes now and then, wondering if it is necessary to update Commit the changes of Cargo.lock all the time

Just commit the change

**Pull request merged**
