### PR TITLE
[prover] upgrade move prover to diem release 1.3

### PR DESCRIPTION
**Pull request by guangyuz**

### CODE REVIEW

**Comment by guangyuz** [comment]
Boogie exited when compile 'Option::is_some<vector>( )'. Below test can reproduce the error. It works fine in diem release v1.2, but fails in the latest build.

```
// Collection.move
address 0x1 {

module Collection {
    use 0x1::Option::{Self, Option};

    spec module {
        pragma verify = true;
        pragma aborts_if_is_strict = true;
    }
    
    struct Collection<T> has key {
        items: Option<vector<T>>,
    }

    fun destroy_empty<T>(c: Collection<T>){
        let Collection{ items } = c;
        Option::destroy_none(items);
    }

    spec destroy_empty {
        aborts_if Option::is_some<vector<T>>(c.items);
    }

}
}

```rust
A bug is reports to Diem and below modules are excluded temporarily:
    prover stdlib[inv-v1]::VMConfig.move
    prover stdlib[inv-v1]::TransactionTimeoutConfig.move
    prover stdlib[inv-v1]::RewardConfig.move
    prover stdlib[inv-v1]::StdlibUpgradeScripts.move
    prover stdlib[inv-v1]::STC.move
    prover stdlib[inv-v1]::ConsensusStrategy.move
    prover stdlib[inv-v1]::Config.move
    prover stdlib[inv-v1]::BlockReward.move
    prover stdlib[inv-v1]::Account.move

**Comment by guangyuz** [comment]
https://github.com/diem/diem/issues/8645

**Review by jolestar — APPROVED** [review]

**Comment by jolestar** [comment]
language/diem-framework/modules/ValidatorConfig.move

```
 /// Returns true if addr has an operator account.
    spec fun spec_has_operator(addr: address): bool {
        Option::is_some(global<ValidatorConfig>(addr).operator_account)
    }
```

这个也在 spec 里用了  Option::is_some

**Comment by guangyuz** [comment]
> language/diem-framework/modules/ValidatorConfig.move
> 
> ```
>  /// Returns true if addr has an operator account.
>     spec fun spec_has_operator(addr: address): bool {
>         Option::is_some(global<ValidatorConfig>(addr).operator_account)
>     }
> ```
> 
> 这个也在 spec 里用了 Option::is_some

Option::is_some is ok. It breaks only when use vector in an option, for example, 'Option::is_some<vector<T>>'.

**Pull request merged**
