### PR TITLE
differentiate gcc-powerpc-linux-gnu package name on different architecture

### PR DESCRIPTION
**Pull request by JerryKwan**
differentiate gcc-powerpc-linux-gnu package name on different
architecture

## Pull request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

-
-
-

### CODE REVIEW

**Comment by JerryKwan** [comment]
Bug fix for issue https://github.com/starcoinorg/starcoin/issues/3433

**Comment by nkysg** [comment]
@JerryKwan hi, there is a script https://github.com/starcoinorg/starcoin/blob/master/scripts/check_commit.sh,  you can run it  
find some format mistakes. Please check it , thks.

**Comment by nkysg** [comment]
@JerryKwan  Hi, I hava a question to ask you。https://github.com/starcoinorg/starcoin/issues/3435 remind ， is `-std=c99` can work? In my computer, I compile use `cargo build --release`, then i use these command
```shell
cd target
find . -name output | grep cryptonight
./release/build/cryptonight-rs-452255b71a5e3640/output
./release/build/cryptonight-rs-452255b71a5e3640.bak/output
```
use `-std=gnu99` in the output file, it shows the C compiler command
```shell
TARGET = Some("x86_64-apple-darwin")
DEBUG = Some("false")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-I" "ext/" "-Wall" "-Wextra" "-maes" "-msse2" "-Ofast" "-fexceptions" "-std=gnu99" "-o" "/Users/YSG/Github/starcoin/target/release/build/cryptonight-rs-452255b71a5e3640/out/ext/c_groestl.o" "-c" "ext/c_groestl.c"
```

use `-std=c99` in the output file, it shows the C compiler command
```shell
DEBUG = Some("false")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2,sse3,ssse3")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-arch" "x86_64" "-I" "ext/" "-Wall" "-Wextra" "-maes" "-msse2" "-Ofast" "-fexceptions" "-std=c99" "-o" "/Users/YSG/Github/starcoin/target/release/build/cryptonight-rs-452255b71a5e3640/out/ext/c_groestl.o" "-c" "ext/c_groestl.c"
```
I think it can work， but i don't have centos7.9. can you help me to try?

**Comment by JerryKwan** [comment]
> scripts/check_commit.sh

@nkysg change the code style accordingly

**Comment by JerryKwan** [comment]
> 

@nkysg 
Have done some test using -std=c99, the following error prompts
```text
  error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "ext/" "-Wall" "-Wextra" "-maes" "-msse2" "-Ofast" "-fexceptions" "-std=c99" "-o" "/home/workspace/starcoin/target/debug/build/cryptonight-rs-c522f4affd0f040f/out/ext/aesb.o" "-c" "ext/aesb.c" with args "cc" did not execute successfully (status code exit status: 1).
```
It might be caused by the cc version.
The version I am using is cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), which version are you using?

**Comment by nkysg** [comment]
> 

May be some mistake in centos7.9, we could use `-std=gnu99` let it run.

**Review by nkysg — APPROVED** [review]

**Pull request merged**
