### PR TITLE
[rpc] add RPC API contract.resolve_module_function_index

### PR DESCRIPTION
**Pull request by coldnight**
Related #3450.

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number:  #3450.

## What is the new behavior?

- Add an new RPC API that could resolve function index from CompiledModule.
- Here is an example invocation in my own environment(deployed a toy [mycounter](https://github.com/starcoinorg/starcoin-cookbook/tree/main/examples/my-counter) contract)
    ```shell
    $ curl 'http://localhost:9850/' -X POST -H 'Content-Type: application/json' --data-raw '{"method":"contract.resolve_module_function_index","params":["0x43c83253e82b2667760caa005bfe4e36::MyCounter", 0],"id":56,"jsonrpc":"2.0"}'
    ```
- The result I got

    ```json
    {
      "jsonrpc": "2.0",
      "result": {
        "args": [
          {
            "doc": "",
            "name": "p0",
            "type_tag": {
              "Reference": [
                false,
                "Signer"
              ]
            }
          }
        ],
        "doc": "",
        "module_name": {
          "address": "0x43c83253e82b2667760caa005bfe4e36",
          "name": "MyCounter"
        },
        "name": "incr",
        "returns": [],
        "ty_args": []
      },
      "id": 56
    }

    ```

### CODE REVIEW

**Comment by coldnight** [comment]
Hold on please, it'll cause panic if the `function_index` is overflow.

**Comment by coldnight** [comment]
> Hold on please, it'll cause panic if the function_index is overflow.

```shell
$  curl 'http://localhost:9851/' -X POST -H 'Content-Type: application/json' --data-raw '{"method":"contract.resolve_module_function_index","params":["0x3c7430c3c2a3979a703f52d3eca3ae67::MyCounter", 4],"id":56,"jsonrpc":"2.0"}'
```

```json
{
  "error": {
    "code": -32603,
    "message": "Function index 4 out of range in ModuleId { address: 0x3c7430c3c2a3979a703f52d3eca3ae67, name: Identifier(\"MyCounter\") }"
  },
  "id": 56,
  "jsonrpc": "2.0"
}
```

**Comment by jolestar** [comment]
@coldnight Please help to add a unit test for `resolve_module_function_index`

**Comment by coldnight** [comment]
@jolestar Unit tests have been added.

**Pull request merged**
